%% JavaScript Type Hierarchy

graph TB
  Object --> Number
  Object --> String
  Object --> Boolean
  Object --> Function
  Object --> Date
  Object --> RegExp
  Object --> Array
  Object --> Math
  Object --> Error
  Object --> JSON
  Object --> ArrayBuffer
  Object --> DataView
  Object --> TypedArray
  Object --> Map
  Object --> WeakMap
  Object --> Set
  Object --> WeakSet
  Object --> Promise
  
  Proxy
  Symbol
  Null_primitive
  Undefined_primitive
  Boolean_primitive
  Number_primitive
  String_primitive