%% Java Type Hierarchy

graph TB
  Object --> Boolean
  Object --> Character
  Object --> Character.Subset
  Character.Subset --> Character.UnicodeBlock
  Object --> Class
  Object --> ClassLoader
  Object --> ClassValue
  Object --> Compiler
  Object --> Enum
  Object --> Math
  Object --> Number
  Number --> Byte
  Number --> Double
  Number --> Float
  Number --> Integer
  Number --> Long
  Number --> Short
  Object --> Package
  Object --> Permission
  Object --> Process
  Object --> ProcessBuilder
  Object --> ProcessBuilder.Redirect
  Object --> Runtime
  Object --> SecurityManager
  Object --> StackTraceElement
  Object --> StrictMath
  Object --> String
  Object --> StringBuffer
  Object --> StringBuilder
  Object --> System
  Object --> Thread
  Object --> ThreadGroup
  Object --> ThreadLocal
  Object --> Throwable
  Throwable --> Error
  Throwable --> Exception
  Object --> Void